@echo off
setlocal enabledelayedexpansion

REM 设置颜色
color 0A

REM 【修改点】添加循环起点标签
:start

echo.
echo ===============================================
echo    shadowrocket to clash格式转换工具
echo ===============================================
echo.

echo.
REM 获取用户输入的文件名（可不带扩展名）
set /p "input_file=请输入要转换的文档文件名（不输入扩展名则默认使用.list）: "

REM 检查文件是否存在（优先尝试.list扩展名）
set "found_file="
if exist "%input_file%" (
    set "found_file=%input_file%"
) else if exist "%input_file%.list" (
    set "found_file=%input_file%.list"
) else if exist "%input_file%.txt" (
    set "found_file=%input_file%.txt"
) else if exist "%input_file%.TXT" (
    set "found_file=%input_file%.TXT"
) else if exist "%input_file%.rule" (
    set "found_file=%input_file%.rule"
)

REM 如果文件不存在，显示错误信息
if "!found_file!"=="" (
    echo 错误：文件 "%input_file%" 不存在！
    echo 已尝试查找以下文件：
    echo   %input_file%
    echo   %input_file%.list（默认扩展名）
    echo   %input_file%.txt
    echo   %input_file%.TXT
    echo   %input_file%.rule
    pause
    REM 【修改点】文件不存在时，跳回起点重新输入，而不是退出
    goto start
)

set "input_file=!found_file!"

REM 提取文件名（不含扩展名）用于输出文件
for %%i in ("!input_file!") do (
    set "output_file=%%~ni.yaml"
)

echo 正在转换 "!input_file!" -> "!output_file!"...
echo.

REM 创建YAML文件并写入头部信息
echo # NAME: ConvertedFrom_!input_file! > "!output_file!"
echo # AUTHOR: Batch Converter >> "!output_file!"
echo # REPO: Generated by batch script >> "!output_file!"
echo # UPDATED: %date% %time% >> "!output_file!"
echo. >> "!output_file!"

REM 写入payload部分
echo payload: >> "!output_file!"

REM 读取输入文件并处理每一行
set line_count=0
set rule_count=0

for /f "usebackq tokens=1* delims=," %%a in ("!input_file!") do (
    set /a line_count+=1
    set "rule_type=%%a"
    set "rule_value=%%b"
    
    REM 去除规则类型和值的空格
    set "rule_type=!rule_type: =!"
    set "rule_value=!rule_value: =!"
    
    REM 跳过空行和注释行（以#开头的行）
    if not "!rule_type!"=="" (
        if not "!rule_type:~0,1!"=="#" (
            REM 写入规则（修复重复，只保留一次）
            echo   - !rule_type!,!rule_value! >> "!output_file!"
            set /a rule_count+=1
        )
    )
)

REM 显示转换结果
echo ===============================================
echo 转换完成！
echo 输入文件: !input_file! （共处理 !line_count! 行）
echo 输出文件: !output_file! （共转换 !rule_count! 条规则）
echo ===============================================
echo.

REM 显示转换后的文件预览
echo 文件前10行预览：
echo -------------------------
for /f "tokens=1* delims=:" %%i in ('findstr /n "^" "!output_file!"') do (
    if %%i leq 10 echo %%j
)
echo -------------------------
echo.

REM 【修改点】询问用户是否继续转换另一个文件
set /p "continue=是否继续转换另一个文件？(y/n): "
if /i "!continue!"=="y" (
    echo.
    goto start
) else (
    echo 程序退出。
    pause
    exit /b 0
)
